openapi: 3.1.0
info:
  title: Kaleo API
  version: '1.0.0'
  description: API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
  

tags:
  - name: login
    description: Operations related to user authentication and login.
  - name: register
    description: Operations related to new user registration.
  - name: users
    description: Operations related to user profiles and management.

paths:
  # Auth paths
  "/api/v1/auth/login":
    $ref: './paths/auth/login.yml'
  "/api/v1/auth/register":
    $ref: './paths/auth/register.yml'
  "/api/v1/auth/oauth/google":
    $ref: './paths/auth/google.yml'
  "/api/v1/auth/oauth/microsoft":
    $ref: './paths/auth/microsoft.yml'

  # User paths
  "/api/v1/users/me":
    $ref: './paths/users.yml'

components:
  schemas:
    LoginRequest:
      $ref: './components/schemas.yml#/components/schemas/LoginRequest'
    RegisterRequest:
      $ref: './components/schemas.yml#/components/schemas/RegisterRequest'
    LoginResponseBody:
      $ref: './components/schemas.yml#/components/schemas/LoginResponseBody'
    OAuthTokenRequest:
      $ref: './components/schemas.yml#/components/schemas/OAuthTokenRequest'
    UserProfile:
      $ref: './components/schemas.yml#/components/schemas/UserProfile'
    DefaultErrorResponse:
      $ref: '../common/default.yml#/components/schemas/DefaultErrorResponse'
  responses:
    LoginResponse:
      $ref: './components/responses.yml#/components/responses/LoginResponse'
    UserProfileResponse:
      $ref: './components/responses.yml#/components/responses/UserProfileResponse'
    BadRequest:
      $ref: '../common/default.yml#/components/responses/BadRequest'
    Unauthorized:
      $ref: '../common/default.yml#/components/responses/Unauthorized'
    Forbidden:
      $ref: '../common/default.yml#/components/responses/Forbidden'
    NotFound:
      $ref: '../common/default.yml#/components/responses/NotFound'
    Conflict:
      $ref: '../common/default.yml#/components/responses/Conflict'
    InternalServerError:
      $ref: '../common/default.yml#/components/responses/InternalServerError'
  securitySchemes:
    BearerAuth:
      $ref: '../common/security.yml#/components/securitySchemes/BearerAuth'