# coding: utf-8

"""
    Kaleo API

    API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from kaleo_core_api_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Kaleo API",
    description="API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
