# coding: utf-8

"""
    Kaleo API

    API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from kaleo_core_api_server.apis.login_api import router as LoginApiRouter
from kaleo_core_api_server.apis.register_api import router as RegisterApiRouter
from kaleo_core_api_server.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="Kaleo API",
    description="API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.",
    version="1.0.0",
)

app.include_router(LoginApiRouter)
app.include_router(RegisterApiRouter)
app.include_router(UsersApiRouter)
