/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaResponse } from './schemaResponse';

/**
 * The server cannot process the request due to client error
 */
export type BadRequestResponse = SchemaResponse;
