/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */

export interface LoginResponseBody {
  access_token?: string;
  token_type?: string;
  expires_in?: number;
  /** @nullable */
  refresh_token?: string | null;
}
