/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */

export type NotFoundResponse = {
  /** @maxLength 2147483647 */
  title?: string;
  /**
   * @minimum 200
   * @maximum 599
   */
  status?: number;
  /** @maxLength 2147483647 */
  detail?: string;
  /** @maxLength 2147483647 */
  type?: string;
  /** @maxLength 2147483647 */
  instance?: string;
  /** @maxLength 2147483647 */
  message?: string;
  [key: string]: unknown;
 };
