/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */

export type UserProfileAuthProvider = typeof UserProfileAuthProvider[keyof typeof UserProfileAuthProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileAuthProvider = {
  local: 'local',
  google: 'google',
  microsoft: 'microsoft',
} as const;
