/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileAuthProvider } from './userProfileAuthProvider';

export interface UserProfile {
  id?: string;
  email?: string;
  name?: string;
  auth_provider?: UserProfileAuthProvider;
}
