/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Kaleo API
 * API Backend para control nutricional y calórico. Incluye login básico, SSO Google/Microsoft y perfil de usuario.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfile } from './userProfile';

/**
 * Perfil del usuario
 */
export type UserProfileResponseResponse = UserProfile;
